package org.staw.datarepository;

public enum Queries{
	
	CREATE_TEST_RUN("INSERT INTO TEST_DETAILS (P_ID, TESTNAME, BROWSER, BROWSER_VERSION, OS, USERID,HOSTNAME,START_TIMESTAMP) VALUES(?,?,?,?,?,?,?,?)"),
	UPDATE_TEST_RUN("UPDATE TEST_DETAILS SET TESTNAME=?, BROWSER=?, BROWSER_VERSION=?, OS=? , USERID=? , HOSTNAME=?, START_TIMESTAMP =? WHERE P_ID=?"),
	GET_TEST_RUN("SELECT P_ID, TESTNAME, BROWSER, BROWSER_VERSION, OS, USERID,HOSTNAME,START_TIMESTAMP FROM  TEST_DETAILS WHERE P_ID=?"),
	
	ADD_TEST_STEP("INSERT INTO TEST_EXECUTION_STEPS (P_ID, EXECUTION_TIME, STEP_NUMBER, KEYWORD, PARAMETERS, DESCRIPTION, RESULT) VALUES(?,?,?,?,?,?,?)"),
	UPDATE_TEST_STEP("UPDATE TEST_EXECUTION_STEPS SET EXECUTION_TIME=?, STEP_NUMBER=?, KEYWORD=?, PARAMETERS=?, DESCRIPTION=?, RESULT=? WHERE P_ID=?"),
	GET_TEST_STEP("SELECT P_ID, EXECUTION_TIME, STEP_NUMBER, KEYWORD, PARAMETERS, DESCRIPTION, RESULT FROM  TEST_EXECUTION_STEPS WHERE P_ID=?"),
	
	ADD_TEST_CONTEXT("INSERT INTO TEST_CONTEXT (P_ID, NAME, VAL) VALUES(?,?,?)"),
	UPDATE_TEST_CONTEXT("UPDATE TEST_CONTEXT SET NAME=?, VAL=? WHERE P_ID=?"),
	GET_TEST_CONTEXT("SELECT P_ID, NAME, VAL FROM  TEST_CONTEXT WHERE P_ID=? AND NAME=?"),
	
	GET_TEST_DATA("SELECT KEY_GROUP,KEY_NAME,VALUE FROM TESTDATA WHERE KEY_NAME=?");
	
	private String sql;
	
	private Queries(String sql){
		this.sql = sql;
	}
	public String getSql(){
		return this.sql;
	}
	public static Queries getQueryType(String type){
		for(Queries item: Queries.values()){
			if(item.name().equalsIgnoreCase(type)) return item;
		}
		return null;
	}
}
