package org.staw.datarepository;

public enum QueryVars{
	
	/*
	 * Insert - Main Tables
	 */
	INSERT_INTO_SCRIPTS("INSERT INTO SCRIPTS VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"),
	INSERT_INTO_SCRIPT_PATH("INSERT INTO SCRIPT_PATH (P_ID, SCRIPT_PATH) VALUES (?,?)"),
	INSERT_INTO_USERS("INSERT INTO SELENIUM_USERS VALUES(?,?,?,?)"),
	INSERT_INTO_CREDIT_CARD("INSERT INTO CREDIT_CARD VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"),
	INSERT_INTO_USER_REGRISTRATION("INSERT INTO USER_REGRISTRATION VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"),
	INSERT_INTO_USER_SALES_FORCE("INSERT INTO SALES_FORCE VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"),
	INSERT_INTO_PROD_APP_SERVERS("INSERT INTO PROD_APP_SERVERS VALUES(?,?,?,?,?,?)"),
	INSERT_INTO_QA_APP_SERVERS("INSERT INTO QA_APP_SERVERS VALUES(?,?,?)"),
	INSERT_INTO_ITEMS("INSERT INTO ITEMS VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"),
	
	INSERT_INTO_THREADS("INSERT INTO THREADS (THREAD, P_ID, TESTNAME, BROWSER, BROWSER_VERSION, OS) VALUES(?,?,?,?,?,?)"),
	INSERT_INTO_MASTER_TABLE("INSERT INTO MASTER_TABLE (P_ID, KEY_VAL, VAL) VALUES(?,?,?)"),
	INSERT_INTO_STEP_LEVEL_REPORT("INSERT INTO STEP_LEVEL_REPORT (P_ID, TSTAMP, STEP_NUMBER, KEYWORD, PARAMETERS, DESCRIPTION, RESULT) VALUES(?,?,?,?,?,?,?)"),
	INSERT_INTO_REPORT_TABLE("INSERT INTO REPORT_TABLE (P_ID, START_TIME, TOTAL_STEPS, STEPS_PASSED, STEPS_FAILED, TOTAL_EXECUTION_TIME, RESULT, BUILD, CONTENT_VERSION, COOKIE) VALUES(?,?,?,?,?,?,?,?,?,?)"),
	INSERT_INTO_RERUN_TABLE("INSERT INTO RERUN_TABLE (CURRENT_THREAD, CURRENT_PID, PREVIOUS_PID) VALUES (?,?,?)"),
	INSERT_INTO_JSERROR_TABLE("INSERT INTO JSERROR (P_ID, TSTAMP, URL, JSERROR) VALUES(?,?,?,?)"),
	INSERT_INTO_COOKIES_TABLE("INSERT INTO COOKIES (P_ID, TSTAMP, NAME, DOMAIN, VALUE) VALUES(?,?,?,?,?)"),
	
	INSERT_INTO_PLANS("INSERT INTO PLANS (PLAN_NAME) VALUES (?)"),
	INSERT_INTO_BUILD("INSERT INTO BUILD (PLAN_ID, BUILD_FULL_KEY, BUILD_KEY, BUILD_NUMBER, BUILD_TIMESTAMP) VALUES (?,?,?,?,?)"),
	INSERT_INTO_BUILD_INFO("INSERT INTO BUILD_INFO (BUILD_ID, BUILD_RESULT_KEY, BUILD_RESULT_URL, BUILD_TRIGGER, BUILD_TEST_ENVIRONMENT, BUILD_BROWSER_PERMUTATION, DURATION, TOTAL_SCRIPTS, TOTAL_PASSED, TOTAL_UNIQUE_SCRIPTS, TOTAL_UNIQUE_PASSED, OUTCOME) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)"),
	INSERT_INTO_BUILD_SCRIPTS("INSERT INTO BUILD_SCRIPTS (BUILD_ID, P_ID) VALUES (?,?)"),
	INSERT_INTO_SALESFORCE_USER_ID("INSERT INTO SALESFORCE_USER_ID(SELENIUM_USER_ID, SALESFORCE_USER_ID) VALUES (?,?)"),
	INSERT_INTO_BUILD_BROWSER_STASTICS("INSERT INTO BUIILD_BROWSER_STATISTICS(BUILD_KEY, BROWSER, BROWSER_VERSION, OS, PASSED, FAILED, PASSED_PERCENT) VALUES (?,?,?,?,?,?,?)"),
	
	/*
	 * Update 
	 */
	UPDATE_SCRIPTS("UPDATE SCRIPTS SET COLUMN_NAME_HERE=1 WHERE SCRIPT_NAME=?"),
	UPDATE_SCRIPT_PATH("UPDATE SCRIPT_PATH SET SCRIPT_PATH=? WHERE P_ID=?"),
	UPDATE_THREADS_VALUES("UPDATE THREADS SET TESTNAME=?, BROWSER=?, BROWSER_VERSION=?, OS=? WHERE P_ID=?"),
	UPDATE_THREADS_TESTNAME("UPDATE THREADS SET TESTNAME=? WHERE P_ID=?"),
	UPDATE_THREADS_BROWSER("UPDATE THREADS SET BROWSER=? WHERE P_ID=?"),
	UPDATE_THREADS_BROWSER_VERSION("UPDATE THREADS SET BROWSER_VERSION=? WHERE P_ID=?"),
	UPDATE_THREADS_OS("UPDATE THREADS SET OS=? WHERE P_ID=?"),
	UPDATE_THREADS_BUILD_FULL_KEY("UPDATE THREADS SET BUILD_FULL_KEY=? WHERE P_ID=?"),
	UPDATE_MASTER_TABLE("UPDATE MASTER_TABLE SET VAL=? WHERE P_ID=? AND KEY_VAL=?"),
	UPDATE_STEP_LEVEL_KEYWORD("UPDATE "
			+ "STEP_LEVEL_REPORT "
			+ "SET "
			+ "KEYWORD=? "
			+ "WHERE "
			+ "P_ID=? "
			+ "AND STEP_NUMBER=?"),
	UPDATE_STEP_LEVEL_PARAMETERS("UPDATE "
			+ "STEP_LEVEL_REPORT "
			+ "SET "
			+ "PARAMETERS=? "
			+ "WHERE "
			+ "P_ID=? "
			+ "AND STEP_NUMBER=?"),
	UPDATE_STEP_LEVEL_DESCRIPTION("UPDATE "
			+ "STEP_LEVEL_REPORT "
			+ "SET "
			+ "DESCRIPTION=? "
			+ "WHERE "
			+ "P_ID=? "
			+ "AND STEP_NUMBER=?"),
	UPDATE_STEP_LEVEL_RESULT("UPDATE "
			+ "STEP_LEVEL_REPORT "
			+ "SET "
			+ "RESULT=? "
			+ "WHERE "
			+ "P_ID=? "
			+ "AND STEP_NUMBER=?"),
	UPDATE_REPORT_TABLE_START_TIME("UPDATE "
			+ "REPORT_TABLE "
			+ "SET "
			+ "START_TIME=? "
			+ "WHERE "
			+ "P_ID=?"),
	UPDATE_REPORT_TABLE_TOTAL_STEPS("UPDATE "
			+ "REPORT_TABLE "
			+ "SET "
			+ "TOTAL_STEPS=? "
			+ "WHERE "
			+ "P_ID=?"),
	UPDATE_REPORT_TABLE_STEPS_PASSED("UPDATE "
			+ "REPORT_TABLE "
			+ "SET "
			+ "STEPS_PASSED=? "
			+ "WHERE "
			+ "P_ID=?"),
	UPDATE_REPORT_TABLE_STEPS_FAILED("UPDATE "
			+ "REPORT_TABLE "
			+ "SET "
			+ "STEPS_FAILED=? "
			+ "WHERE "
			+ "P_ID=?"),
	UPDATE_REPORT_TABLE_TOTAL_EXECUTION_TIME("UPDATE "
			+ "REPORT_TABLE "
			+ "SET "
			+ "TOTAL_EXECUTION_TIME=? "
			+ "WHERE "
			+ "P_ID=?"),
	UPDATE_REPORT_TABLE_RESULT("UPDATE "
			+ "REPORT_TABLE "
			+ "SET "
			+ "RESULT=? "
			+ "WHERE "
			+ "P_ID=?"),
	UPDATE_REPORT_TABLE_SAUCE_VIDEO("UPDATE "
			+ "REPORT_TABLE "
			+ "SET "
			+ "SAUCE_VIDEO=? "
			+ "WHERE "
			+ "P_ID=?"),
	UPDATE_REPORT_TABLE_SPLUNK_SESSION("UPDATE "
			+ "REPORT_TABLE "
			+ "SET "
			+ "SPLUNK_SESSION=? "
			+ "WHERE "
			+ "P_ID=?"),
	UPDATE_REPORT_TABLE_SILO("UPDATE "
			+ "REPORT_TABLE "
			+ "SET "
			+ "SILO=? "
			+ "WHERE "
			+ "P_ID=?"),
	UPDATE_REPORT_TABLE_BUILD("UPDATE "
			+ "REPORT_TABLE "
			+ "SET "
			+ "BUILD=? "
			+ "WHERE "
			+ "P_ID=?"),
	UPDATE_REPORT_TABLE_CONTENT_VERSION("UPDATE "
			+ "REPORT_TABLE "
			+ "SET "
			+ "CONTENT_VERSION=? "
			+ "WHERE "
			+ "P_ID=?"),
	UPDATE_REPORT_TABLE_O_COOKIE("UPDATE "
			+ "REPORT_TABLE "
			+ "SET "
			+ "O_COOKIE=? "
			+ "WHERE "
			+ "P_ID=?"),
	UPDATE_REPORT_TABLE_SET_TO_FAILED("UPDATE REPORT_TABLE SET RESULT = 'Failed' WHERE RESULT='N/A'"),
	UPDATE_RERUN_TABLE_CURRENT_PID_WITH_PREVIOUS_PID("UPDATE RERUN_TABLE SET PREVIOUS_PID=? WHERE CURRENT_PID=?"),
	
	GET_TEST_DATA_BY_KEY("SELECT VALUE FROM TESTDATA WHERE KEY_NAME=?"),
	/*
	 * Get
	 */
	GET_COOKIES_VALUE_BY_COOKIE_AND_PID("SELECT VALUE FROM COOKIES WHERE P_ID=? AND NAME=?"),
	GET_COOKIES_ALL_COOKIES_BY_PID("SELECT NAME, DOMAIN, VALUE FROM COOKIES WHERE P_ID=?"),
	GET_COOKIES_ALL_INFORMATION("SELECT TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION, TR.OS, CK.NAME, CK.DOMAIN, CK.VALUE FROM COOKIES CK JOIN THREADS TR ON TR.P_ID=CK.P_ID JOIN BUILD_SCRIPTS BS ON TR.P_ID=BS.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE BD.BUILD_FULL_KEY=? ORDER BY TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION"),
	
	GET_JSERRORS_ALL_INFORMATION("SELECT TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION, TR.OS, JSR.TSTAMP, JSR.URL, JSR.JSERROR FROM JSERROR JSR JOIN THREADS TR ON TR.P_ID = JSR.P_ID JOIN BUILD_SCRIPTS BS ON BS.P_ID = TR.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE BD.BUILD_FULL_KEY = ? ORDER BY TR.P_ID"),
	GET_JSERRORS_SIZE("SELECT COUNT(*) FROM JSERROR JSR JOIN BUILD_SCRIPTS BS ON BS.P_ID=JSR.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE BD.BUILD_FULL_KEY=?"),
	
	GET_RERUN_TABLE_PREVIOUS_PID_FOR_CURRENT_PID("SELECT PREVIOUS_PID FROM RERUN_TABLE WHERE CURRENT_PID=?"),
	GET_RERUN_TABLE_ORIGINAL_AND_RERUN_USING_ORIGINAL_PID("SELECT PREVIOUS_PID AS ORIGINAL, CURRENT_PID AS RERUN FROM RERUN_TABLE WHERE PREVIOUS_PID=?"),
	
	GET_THREADS_ALL_SCRIPTS_RUN_IN_SUITE_INCLUDING_RERUN("SELECT TR.P_ID FROM THREADS TR JOIN BUILD_SCRIPTS BS ON TR.P_ID=BS.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE BD.BUILD_FULL_KEY=?"),
	GET_THREADS_ALL_SCRIPTS_RUN_IN_SUITE_NOT_INCLUDING_RERUN_COUNT("SELECT COUNT(*) FROM (SELECT TR.TESTNAME FROM THREADS TR JOIN BUILD_SCRIPTS BS ON BS.P_ID=TR.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE BD.BUILD_FULL_KEY=? GROUP BY TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION, TR.OS)"),
	GET_THREADS_UNIQUE_SCRIPTS_RUN_IN_SUITE("SELECT DISTINCT(TR.TESTNAME) FROM THREADS TR JOIN BUILD_SCRIPTS BS ON TR.P_ID=BS.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE BD.BUILD_FULL_KEY=?"),
	GET_THREADS_UNIQUE_PID("SELECT DISTINCT TR.P_ID, TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION FROM THREADS TR JOIN BUILD_SCRIPTS BS ON TR.P_ID=BS.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE BD.BUILD_FULL_KEY=?"),
	GET_THREADS_INFORMATION("SELECT DISTINCT TR.P_ID, TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION FROM THREADS TR JOIN BUILD_SCRIPTS BS ON BS.P_ID=TR.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE BD.BUILD_FULL_KEY=? ORDER BY TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION"),
	GET_THREADS_TESTNAME("SELECT TESTNAME FROM THREADS WHERE P_ID=?"),
	GET_THREADS_BROWSER("SELECT BROWSER FROM THREADS WHERE P_ID=?"),
	GET_THREADS_BROWSER_VERSION("SELECT BROWSER_VERSION FROM THREADS WHERE P_ID=?"),
	GET_THREADS_OS("SELECT OS FROM THREADS WHERE P_ID=?"),
	GET_THREADS_THREAD("SELECT THREAD FROM THREADS WHERE P_ID=?"),
	GET_THREADS_INFO_BY_PID("SELECT TESTNAME, BROWSER, BROWSER_VERSION, OS FROM THREADS WHERE P_ID=?"),
	GET_THREADS_SCRIPT_RESULT_BY_SCRIPT_INFORMATION("SELECT RT.RESULT, RT.O_COOKIE, RT.BUILD, RT.CONTENT_VERSION, RT.P_ID FROM THREADS TR , REPORT_TABLE RT, BUILD_SCRIPTS BS, BUILD BD WHERE TR.P_ID=RT.P_ID AND TR.P_ID=BS.P_ID AND BS.BUILD_ID=BD.ID AND TR.TESTNAME=? AND TR.BROWSER=? AND TR.BROWSER_VERSION=? AND TR.OS=? AND BD.BUILD_FULL_KEY=? ORDER BY TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION, RT.START_TIME"),
	GET_THREADS_TABLE_ALL_BROWSERS_RUN_IN_SUITE("SELECT TR.BROWSER, TR.BROWSER_VERSION, TR.OS FROM THREADS TR JOIN BUILD_SCRIPTS BS ON TR.P_ID=BS.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID JOIN REPORT_TABLE RT ON TR.P_ID=RT.P_ID WHERE BD.BUILD_FULL_KEY=? GROUP BY TR.BROWSER, TR.BROWSER_VERSION, TR.OS ORDER BY TR.BROWSER, TR.BROWSER_VERSION, TR.OS"),
	GET_THREADS_TABLE_BROWSER_RESULT_COUNT_BY_BROWSER_OS_INFO("SELECT COUNT(*) AS BROWSER_PASSED FROM THREADS TR JOIN BUILD_SCRIPTS BS ON TR.P_ID=BS.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID JOIN REPORT_TABLE RT ON TR.P_ID=RT.P_ID WHERE RESULT = 'PASSED' AND BD.BUILD_FULL_KEY=? AND TR.BROWSER=? AND TR.BROWSER_VERSION=? AND TR.OS=?"),
	GET_THREADS_P_ID_BY_TEST_NAME_AND_BUILD_KEY("SELECT TR.P_ID FROM THREADS TR JOIN BUILD_SCRIPTS BS ON TR.P_ID=BS.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE BD.BUILD_FULL_KEY=? AND TR.TESTNAME=?"),
	
	GET_MASTER_TABLE_COUNT_OF_KEY("SELECT COUNT(*) FROM (SELECT DISTINCT(TR.TESTNAME) FROM MASTER_TABLE MT JOIN THREADS TR ON MT.P_ID = TR.P_ID JOIN BUILD_SCRIPTS BS ON MT.P_ID=BS.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE MT.KEY_VAL=? AND BD.BUILD_FULL_KEY=?)"),
	GET_MASTER_TABLE_COUNT_OF_KEY_AND_VALUE("SELECT COUNT(*) FROM (SELECT DISTINCT(TR.TESTNAME) FROM MASTER_TABLE MT JOIN THREADS TR ON MT.P_ID = TR.P_ID JOIN BUILD_SCRIPTS BS ON MT.P_ID=BS.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE TR.P_ID NOT IN (SELECT RRT.PREVIOUS_PID FROM RERUN_TABLE RRT) AND MT.KEY_VAL=? AND MT.VAL=? AND BD.BUILD_FULL_KEY=?)"),
	GET_MASTER_TABLE_JAVA_SCRIP_ERRORS("SELECT TR.P_ID, TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION, TR.OS, MT.KEY_VAL, MT.VAL FROM MASTER_TABLE MT JOIN THREADS TR ON TR.P_ID=MT.P_ID WHERE MT.KEY_VAL='jsErrorIncrementValue' OR MT.KEY_VAL LIKE 'jsErrors%' ORDER BY TR.P_ID"),
	GET_MASTER_TABLE_APP_SERVER_URL("SELECT MT.VAL FROM MASTER_TABLE MT JOIN THREADS TR ON TR.P_ID=MT.P_ID WHERE TR.TESTNAME=? AND MT.KEY_VAL='appServerUrl'"),
	GET_MASTER_TABLE_VALUE("SELECT VAL FROM MASTER_TABLE WHERE P_ID=? AND KEY_VAL=?"),
	GET_MASTER_TABLE_INFO_OF_KEY("SELECT * FROM MASTER_TABLE WHERE KEY_VAL=?"),
	GET_MASTER_TABLE_PROD_APP_SERVER_SILO_BY_PID("SELECT PAS.SILO FROM MASTER_TABLE MT JOIN PROD_APP_SERVERS PAS ON PAS.URL=MT.VAL WHERE MT.KEY_VAL='appServerUrl' AND MT.P_ID=?"),
	GET_MASTER_TABLE_QA_APP_SERVER_SILO_BY_PID("SELECT QAS.SILO FROM MASTER_TABLE MT JOIN QA_APP_SERVERS QAS ON QAS.URL=MT.VAL WHERE MT.KEY_VAL='appServerUrl' AND MT.P_ID=?"),
	GET_MASTER_TABLE_PROD_APP_SERVER_SILO_AND_COMPONENT("SELECT PAS.SILO, PAS.COMPONENT FROM PROD_APP_SERVERS PAS JOIN MASTER_TABLE MT ON MT.VAL=PAS.URL JOIN THREADS TR ON TR.P_ID=MT.P_ID WHERE MT.KEY_VAL='appServerUrl' AND TR.TESTNAME=? AND TR.P_ID=?"),
	GET_MASTER_TABLE_QA_APP_SERVER_SILO_AND_COMPONENT("SELECT QAS.SILO FROM QA_APP_SERVERS QAS JOIN MASTER_TABLE MT ON MT.VAL=QAS.URL JOIN THREADS TR ON TR.P_ID=MT.P_ID WHERE MT.KEY_VAL='appServerUrl' AND TR.TESTNAME=? AND TR.P_ID=?"),
	GET_MASTER_TABLE_PROD_APP_SERVER_URL("SELECT PAS.URL FROM PROD_APP_SERVERS PAS JOIN MASTER_TABLE MT ON MT.VAL=PAS.URL JOIN THREADS TR ON TR.P_ID=MT.P_ID WHERE MT.KEY_VAL='appServerUrl' AND TR.TESTNAME=? AND TR.P_ID=?"),
	GET_MASTER_TABLE_QA_APP_SERVER_URL("SELECT QAS.URL FROM QA_APP_SERVERS QAS JOIN MASTER_TABLE MT ON MT.VAL=QAS.URL JOIN THREADS TR ON TR.P_ID=MT.P_ID WHERE MT.KEY_VAL='appServerUrl' AND TR.TESTNAME=? AND TR.P_ID=?"),
	
	
	GET_STEP_LEVEL_REPORT_VALUES_BY_P_ID("SELECT SLT.STEP_NUMBER, SLT.KEYWORD, SLT.PARAMETERS, SLT.DESCRIPTION, SLT.RESULT FROM STEP_LEVEL_REPORT SLT JOIN THREADS TR ON SLT.P_ID = TR.P_ID WHERE TR.P_ID=? ORDER BY TR.TESTNAME, SLT.STEP_NUMBER"),
	GET_STEP_LEVEL_KEYWORD("SELECT "
			+ "KEYWORD "
			+ "FROM " 
			+ "STEP_LEVEL_REPORT "
			+ "WHERE "
			+ "P_ID=? "
			+ "AND STEP_NUMBER=? "),
	GET_STEP_LEVEL_PARAMETERS("SELECT "
			+ "PARAMETERS "
			+ "FROM "
			+ "STEP_LEVEL_REPORT "
			+ "WHERE "
			+ "P_ID=? "
			+ "AND STEP_NUMBER=? "),
	GET_STEP_LEVEL_DESCRIPTION("SELECT "
			+ "DESCRIPTION "
			+ "FROM "
			+ "STEP_LEVEL_REPORT "
			+ "WHERE "
			+ "P_ID=? "
			+ "AND STEP_NUMBER=? "),
	GET_STEP_LEVEL_RESULT("SELECT "
			+ "RESULT "
			+ "FROM "
			+ "STEP_LEVEL_REPORT "
			+ "WHERE "
			+ "P_ID=? "
			+ "AND STEP_NUMBER=? "),
	
	GET_REPORT_TABLE_START_TIME("SELECT "
			+ "START_TIME "
			+ "FROM "
			+ "REPORT_TABLE "
			+ "WHERE "
			+ "P_ID=? "),
	GET_REPORT_TABLE_TOTAL_STEPS("SELECT "
			+ "TOTAL_STEPS "
			+ "FROM "
			+ "REPORT_TABLE "
			+ "WHERE "
			+ "P_ID=? "),
	GET_REPORT_TABLE_STEPS_PASSED("SELECT "
			+ "STEPS_PASSED "
			+ "FROM "
			+ "REPORT_TABLE "
			+ "WHERE "
			+ "P_ID=? "),
	GET_REPORT_TABLE_STEPS_FAILED("SELECT "
			+ "STEPS_FAILED "
			+ "FROM "
			+ "REPORT_TABLE "
			+ "WHERE "
			+ "P_ID=? "),
	GET_REPORT_TABLE_TOTAL_EXECUTION_TIME("SELECT "
			+ "TOTAL_EXECUTION_TIME "
			+ "FROM "
			+ "REPORT_TABLE "
			+ "WHERE "
			+ "P_ID=? "),
	GET_REPORT_TABLE_RESULT("SELECT "
			+ "RESULT "
			+ "FROM "
			+ "REPORT_TABLE "
			+ "WHERE "
			+ "P_ID=? "),
	GET_REPORT_TABLE_SAUCE_VIDEO("SELECT "
			+ "SAUCE_VIDEO "
			+ "FROM "
			+ "REPORT_TABLE "
			+ "WHERE "
			+ "P_ID=? "),
	GET_REPORT_TABLE_SPLUNK_SESSION("SELECT "
			+ "SPLUNK_SESSION "
			+ "FROM "
			+ "REPORT_TABLE "
			+ "WHERE "
			+ "P_ID=? "),
	GET_REPORT_TABLE_SILO("SELECT "
			+ "SILO "
			+ "FROM "
			+ "REPORT_TABLE "
			+ "WHERE "
			+ "P_ID=? "),
	GET_REPORT_TABLE_BUILD("SELECT "
			+ "BUILD "
			+ "FROM "
			+ "REPORT_TABLE "
			+ "WHERE "
			+ "P_ID=? "),
	GET_REPORT_TABLE_CONTENT_VERSION("SELECT "
			+ "START_TIME "
			+ "FROM "
			+ "REPORT_TABLE "
			+ "WHERE "
			+ "P_ID=? "),
	GET_REPORT_TABLE_O_COOKIE("SELECT "
			+ "START_TIME "
			+ "FROM "
			+ "REPORT_TABLE "
			+ "WHERE "
			+ "P_ID=? "),
	GET_REPORT_TABLE_RESULT_BY_TESTNAME("SELECT TR.BROWSER, TR.BROWSER_VERSION, TR.OS, RT.RESULT FROM REPORT_TABLE RT JOIN THREADS TR ON RT.P_ID=TR.P_ID WHERE TR.TESTNAME=? ORDER BY TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION, TR.OS, RT.START_TIME"),
	GET_REPORT_TABLE_RESULT_BY_PID("SELECT RESULT FROM REPORT_TABLE WHERE P_ID=?"),
	GET_REPORT_TABLE_TOTAL_BROWSERS_FROM_SUITE("SELECT TR.BROWSER, TR.BROWSER_VERSION, TR.OS FROM THREADS TR JOIN BUILD_SCRIPTS BS ON TR.P_ID=BS.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID JOIN REPORT_TABLE ON TR.P_ID=RT.P_ID WHERE BD.BUILD_FULL_KEY=? GROUP BY BROWSER, BROWSER_VERSION, OS ORDER BY BROWSER, BROWSER_VERSION, OS"),
	GET_REPORT_ALL_INFORMATION("SELECT TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION, TR.OS, RT.START_TIME, RT.TOTAL_STEPS, RT.STEPS_PASSED, RT.STEPS_FAILED, RT.TOTAL_EXECUTION_TIME, RT.RESULT, RT.SAUCE_VIDEO, RT.SPLUNK_SESSION, RT.SILO, RT.BUILD, RT.CONTENT_VERSION, RT.O_COOKIE, TR.P_ID FROM THREADS TR JOIN REPORT_TABLE RT ON TR.P_ID=RT.P_ID WHERE TR.P_ID=? ORDER BY TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION, RT.START_TIME"),
	GET_REPORT_ALL_PID("SELECT RT.P_ID FROM THREADS TR JOIN REPORT_TABLE RT ON TR.P_ID=RT.P_ID ORDER BY TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION, RT.START_TIME"),
	GET_REPORT_ALL_INFORMATION_BY_PID("SELECT TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION, TR.OS, RT.START_TIME, RT.TOTAL_STEPS, RT.STEPS_PASSED, RT.STEPS_FAILED, RT.TOTAL_EXECUTION_TIME, RT.RESULT, RT.SAUCE_VIDEO, RT.SPLUNK_SESSION, RT.SILO, RT.BUILD, RT.CONTENT_VERSION, RT.O_COOKIE, TR.P_ID FROM THREADS TR JOIN REPORT_TABLE RT ON TR.P_ID=RT.P_ID WHERE RT.P_ID=? ORDER BY TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION, RT.START_TIME"),
	GET_REPORT_TABLE_ALL_INFORMATION_BY_TESTNAME_BROWSER_BROWSER_VERION_OS("SELECT RT.START_TIME, RT.TOTAL_EXECUTION_TIME, RT.RESULT, RT.SAUCE_VIDEO, RT.SPLUNK_SESSION, RT.SILO, RT.BUILD FROM THREADS TR, REPORT_TABLE RT, BUILD_SCRIPTS BS, BUILD BD WHERE TR.P_ID=RT.P_ID AND TR.P_ID=BS.P_ID AND BS.BUILD_ID=BD.ID AND TR.TESTNAME=? AND TR.BROWSER=? AND TR.BROWSER_VERSION=? AND TR.OS=? AND BD.BUILD_FULL_KEY=? ORDER BY TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION, RT.START_TIME"),
	GET_REPORT_BUILD_NUMBER("SELECT DISTINCT RT.BUILD FROM REPORT_TABLE RT JOIN BUILD_SCRIPTS BS ON BS.P_ID=RT.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE RT.BUILD <> 'N/A' AND BD.BUILD_FULL_KEY=?"),
	GET_REPORT_SILO("SELECT DISTINCT SILO FROM REPORT_TABLE WHERE BUILD <> 'N/A'"),
	GET_REPORT_CONTENT_VERSION("SELECT DISTINCT CONTENT_VERSION FROM REPORT_TABLE WHERE BUILD <> 'N/A'"),
	GET_REPORT_O_COOKIE("SELECT DISTINCT O_COOKIE FROM REPORT_TABLE WHERE BUILD <> 'N/A'"),
	GET_REPORT_LIST_OF_ALL_TEST_PASSED("SELECT RT.P_ID FROM REPORT_TABLE RT JOIN THREADS TR ON RT.P_ID = TR.P_ID JOIN BUILD_SCRIPTS BS ON TR.P_ID=BS.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE RT.RESULT ='PASSED' AND BD.BUILD_FULL_KEY=?"),
	GET_REPORT_LIST_OF_ALL_TEST_FAILED("SELECT RT.P_ID FROM REPORT_TABLE RT JOIN THREADS TR ON RT.P_ID = TR.P_ID JOIN BUILD_SCRIPTS BS ON TR.P_ID=BS.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE RT.RESULT ='FAILED' AND BD.BUILD_FULL_KEY=?"),
	GET_REPORT_TOTAL_STEPS_PASSED("SELECT SUM(RT.STEPS_PASSED) FROM REPORT_TABLE RT JOIN THREADS TR ON TR.P_ID = RT.P_ID JOIN BUILD_SCRIPTS BS ON BS.P_ID=TR.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE BD.BUILD_FULL_KEY=?"),
	GET_REPORT_TOTAL_STEPS("SELECT SUM(RT.TOTAL_STEPS) FROM REPORT_TABLE RT JOIN THREADS TR ON TR.P_ID = RT.P_ID JOIN BUILD_SCRIPTS BS ON BS.P_ID=TR.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE BD.BUILD_FULL_KEY=?"),
	GET_REPORT_APP_SERVER_INFORMATION_BY_URL("SELECT TR.TESTNAME, RT.RESULT, RT.SILO, RT.BUILD, RT.CONTENT_VERSION, RT.O_COOKIE FROM MASTER_TABLE MT JOIN BUILD_SCRIPTS BS ON BS.P_ID=MT.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID JOIN REPORT_TABLE RT ON RT.P_ID=MT.P_ID JOIN THREADS TR ON TR.P_ID = MT.P_ID WHERE MT.VAL=? AND BD.BUILD_FULL_KEY=? ORDER BY RT.START_TIME ASC"),
	GET_ALL_SCRIPTS("SELECT * FROM SCRIPTS"),
	GET_SCRIPTS_FOR_LOCAL_DEV_REGRESSION("SELECT SCRIPT_NAME FROM SCRIPTS WHERE LOCAL_DEV_REGRESSION=1"),
	
	
	GET_SELENIUM_USER_USER_AND_PASSWORD("SELECT SEL_USER, PASSWORD FROM SELENIUM_USERS WHERE USER_TYPE=? AND ENVIRONMENT=?"),
	
	GET_WEB_KS_ORDER_ID("Select WEB_KS_ORDER_NUMBER FROM WEB_KS_ORDER_NUMBERS A, WEB_KS_ORDER_DETAILS B WHERE A.WEB_KS_ID = B.WEB_KS_ID AND WEB_KS_TYPE=? AND WEB_KS_ENVIRONMENT=?"),
	
	GET_SELENIUM_USER_USER_ID("SELECT USER_ID FROM SELENIUM_USERS WHERE SEL_USER=? AND ENVIRONMENT=?"),
	
	GET_SALESFORCE_USER_ID("SELECT SALESFORCE_USER_ID FROM SALESFORCE_USER_ID WHERE SELENIUM_USER_ID=?"),
	
	/*
	 * BROWSER/EMULATORS
	 */
	GET_BROWSERS_ENV_OPTIONS("SELECT BROWSER, BROWSER_VERSION, OS FROM BROWSERS WHERE KEY_VAL=?"),
	GET_EMULATORS_ENV_OPTIONS("SELECT DEVICE_NAME, EMULATOR, EMULATOR_VERSION FROM EMULATORS WHERE KEY_VAL=?"),
		
	/**
	 * Network Analytics
	 */
	GET_NETWORK_DATA_SCRIPT_VALUES_FROM_PAGE_AND_SCRIPT_NAME("SELECT ND_ID, NAME, METHOD, FIELD FROM NETWORK_DATA_SCRIPT WHERE PAGE=? AND SCRIPT_ID=?"),
	GET_NETWORK_DATA_FIELDS_FROM_ND_ID("SELECT PARAMETER_NAME, PARAMETER_VALUE FROM NETWORK_DATA WHERE ND_ID=?"),
	
	/*
	 *BROWSER STATISTICS
	 */
	GET_BUILD_BROWSER_STATISTICS("SELECT BROWSER, BROWSER_VERSION, OS, PASSED, FAILED, PASSED_PERCENT FROM BUIILD_BROWSER_STATISTICS WHERE BUILD_KEY=?");
	
	private String sql;
	
	private QueryVars(String sql){
		this.sql = sql;
	}
	public String getSql(){
		return this.sql;
	}
	public static QueryVars getQueryType(String type){
		for(QueryVars tp: QueryVars.values()){
			if(tp.name().equalsIgnoreCase(type)) return tp;
		}
		return null;
	}
}
