package org.staw.datarepository;

public enum QueryVars{
	/*
	 * Create
	 */
	CREATE_THREADS_TABLE("CREATE TABLE IF NOT EXISTS THREADS( ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, THREAD INT NOT NULL, P_ID VARCHAR(255) NOT NULL, TESTNAME VARCHAR(255) NOT NULL, BROWSER VARCHAR(255) NOT NULL, BROWSER_VERSION VARCHAR(255) NOT NULL, OS VARCHAR(255) NOT NULL, PRIMARY KEY(ID), CONSTRAINT `FK_THREADS` FOREIGN KEY (P_ID) REFERENCES BUILD_SCRIPTS (P_ID) ON DELETE CASCADE ON UPDATE RESTRICT )"),
	CREATE_MASTER_TABLE("CREATE TABLE IF NOT EXISTS MASTER_TABLE( ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, P_ID VARCHAR(255) NOT NULL, KEY_VAL VARCHAR(255) NOT NULL, VAL VARCHAR(2000) NOT NULL, JSERROR VARCHAR(255) NOT NULL, PRIMARY KEY(ID), CONSTRAINT `FK_MASTER_TABLE` FOREIGN KEY (P_ID) REFERENCES BUILD_SCRIPTS (P_ID) ON DELETE CASCADE ON UPDATE RESTRICT )"),
	CREATE_STEP_LEVEL_REPORT("CREATE TABLE IF NOT EXISTS STEP_LEVEL_REPORT( ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, P_ID VARCHAR(255) NOT NULL, TSTAMP TIMESTAMP NOT NULL, STEP_NUMBER INT NOT NULL, KEYWORD VARCHAR (255) NOT NULL, PARAMETERS VARCHAR (255) NOT NULL, DESCRIPTION VARCHAR (255) NOT NULL, RESULT VARCHAR (255) NOT NULL, PRIMARY KEY(ID), CONSTRAINT `FK_STEP_LEVEL_REPORT` FOREIGN KEY (P_ID) REFERENCES BUILD_SCRIPTS (P_ID) ON DELETE CASCADE ON UPDATE RESTRICT )"),
	CREATE_REPORT_TABLE("CREATE TABLE IF NOT EXISTS REPORT_TABLE( ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, P_ID VARCHAR(255) NOT NULL, START_TIME TIMESTAMP NOT NULL, TOTAL_STEPS INT NOT NULL, STEPS_PASSED INT NOT NULL, STEPS_FAILED INT NOT NULL, TOTAL_EXECUTION_TIME VARCHAR(255) NOT NULL, RESULT VARCHAR(255) NOT NULL, SAUCE_VIDEO VARCHAR(255) NOT NULL, SPLUNK_SESSION VARCHAR(255) NOT NULL, SILO VARCHAR(255) NOT NULL, BUILD VARCHAR(255) NOT NULL, CONTENT_VERSION VARCHAR(255) NOT NULL, O_COOKIE VARCHAR(255) NOT NULL, PRIMARY KEY(ID), CONSTRAINT `FK_REPORT_TABLE` FOREIGN KEY (P_ID) REFERENCES BUILD_SCRIPTS (P_ID) ON DELETE CASCADE ON UPDATE RESTRICT )"),
	CREATE_RERUN_TABLE("CREATE TABLE IF NOT EXISTS RERUN_TABLE( ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, CURRENT_THREAD INT NOT NULL, CURRENT_PID VARCHAR(255) NOT NULL, PREVIOUS_PID VARCHAR (255) NOT NULL, PRIMARY KEY(ID), CONSTRAINT `FK_RERUN_TABLE` FOREIGN KEY (CURRENT_PID) REFERENCES BUILD_SCRIPTS (P_ID) ON DELETE CASCADE ON UPDATE RESTRICT )"),
	CREATE_JSERROR_TABLE("CREATE TABLE IF NOT EXISTS JSERROR( ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, P_ID VARCHAR(255) NOT NULL, TSTAMP TIMESTAMP NOT NULL, URL VARCHAR(255) NOT NULL, JSERROR VARCHAR(255) NOT NULL, PRIMARY KEY(ID), CONSTRAINT `FK_JSERROR` FOREIGN KEY (P_ID) REFERENCES BUILD_SCRIPTS (P_ID) ON DELETE CASCADE ON UPDATE RESTRICT )"),
	CREATE_COOKIE_TABLE("CREATE TABLE IF NOT EXISTS COOKIES( ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, P_ID VARCHAR(255) NOT NULL, TSTAMP TIMESTAMP NOT NULL, NAME VARCHAR(255) NOT NULL, DOMAIN VARCHAR(255) NOT NULL, VALUE VARCHAR(255) NOT NULL, PRIMARY KEY(ID), CONSTRAINT `FK_COOKIES` FOREIGN KEY (P_ID) REFERENCES BUILD_SCRIPTS (P_ID) ON DELETE CASCADE ON UPDATE RESTRICT )"),
	
	/*
	 * Insert - Main Tables
	 */
	INSERT_INTO_SCRIPTS("INSERT INTO SCRIPTS VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"),
	INSERT_INTO_SCRIPT_PATH("INSERT INTO SCRIPT_PATH (P_ID, SCRIPT_PATH) VALUES (?,?)"),
	INSERT_INTO_USERS("INSERT INTO SELENIUM_USERS VALUES(?,?,?,?)"),
	INSERT_INTO_CREDIT_CARD("INSERT INTO CREDIT_CARD VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"),
	INSERT_INTO_USER_REGRISTRATION("INSERT INTO USER_REGRISTRATION VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"),
	INSERT_INTO_USER_SALES_FORCE("INSERT INTO SALES_FORCE VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"),
	INSERT_INTO_PROD_APP_SERVERS("INSERT INTO PROD_APP_SERVERS VALUES(?,?,?,?,?,?)"),
	INSERT_INTO_QA_APP_SERVERS("INSERT INTO QA_APP_SERVERS VALUES(?,?,?)"),
	INSERT_INTO_ITEMS("INSERT INTO ITEMS VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"),
	
	INSERT_INTO_THREADS("INSERT INTO THREADS (THREAD, P_ID, TESTNAME, BROWSER, BROWSER_VERSION, OS) VALUES(?,?,?,?,?,?)"),
	INSERT_INTO_MASTER_TABLE("INSERT INTO MASTER_TABLE (P_ID, KEY_VAL, VAL) VALUES(?,?,?)"),
	INSERT_INTO_STEP_LEVEL_REPORT("INSERT INTO STEP_LEVEL_REPORT (P_ID, TSTAMP, STEP_NUMBER, KEYWORD, PARAMETERS, DESCRIPTION, RESULT) VALUES(?,?,?,?,?,?,?)"),
	INSERT_INTO_REPORT_TABLE("INSERT INTO REPORT_TABLE (P_ID, START_TIME, TOTAL_STEPS, STEPS_PASSED, STEPS_FAILED, TOTAL_EXECUTION_TIME, RESULT, BUILD, CONTENT_VERSION, COOKIE) VALUES(?,?,?,?,?,?,?,?,?,?)"),
	INSERT_INTO_RERUN_TABLE("INSERT INTO RERUN_TABLE (CURRENT_THREAD, CURRENT_PID, PREVIOUS_PID) VALUES (?,?,?)"),
	INSERT_INTO_JSERROR_TABLE("INSERT INTO JSERROR (P_ID, TSTAMP, URL, JSERROR) VALUES(?,?,?,?)"),
	INSERT_INTO_COOKIES_TABLE("INSERT INTO COOKIES (P_ID, TSTAMP, NAME, DOMAIN, VALUE) VALUES(?,?,?,?,?)"),
	
	INSERT_INTO_PLANS("INSERT INTO PLANS (PLAN_NAME) VALUES (?)"),
	INSERT_INTO_BUILD("INSERT INTO BUILD (PLAN_ID, BUILD_FULL_KEY, BUILD_KEY, BUILD_NUMBER, BUILD_TIMESTAMP) VALUES (?,?,?,?,?)"),
	INSERT_INTO_BUILD_INFO("INSERT INTO BUILD_INFO (BUILD_ID, BUILD_RESULT_KEY, BUILD_RESULT_URL, BUILD_TRIGGER, BUILD_TEST_ENVIRONMENT, BUILD_BROWSER_PERMUTATION, DURATION, TOTAL_SCRIPTS, TOTAL_PASSED, TOTAL_UNIQUE_SCRIPTS, TOTAL_UNIQUE_PASSED, OUTCOME) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)"),
	INSERT_INTO_BUILD_SCRIPTS("INSERT INTO BUILD_SCRIPTS (BUILD_ID, P_ID) VALUES (?,?)"),
	INSERT_INTO_SALESFORCE_USER_ID("INSERT INTO SALESFORCE_USER_ID(SELENIUM_USER_ID, SALESFORCE_USER_ID) VALUES (?,?)"),
	INSERT_INTO_BUILD_BROWSER_STASTICS("INSERT INTO BUIILD_BROWSER_STATISTICS(BUILD_KEY, BROWSER, BROWSER_VERSION, OS, PASSED, FAILED, PASSED_PERCENT) VALUES (?,?,?,?,?,?,?)"),
	
	/*
	 * Update 
	 */
	UPDATE_SCRIPTS("UPDATE SCRIPTS SET COLUMN_NAME_HERE=1 WHERE SCRIPT_NAME=?"),
	UPDATE_SCRIPT_PATH("UPDATE SCRIPT_PATH SET SCRIPT_PATH=? WHERE P_ID=?"),
	UPDATE_THREADS_VALUES("UPDATE THREADS SET TESTNAME=?, BROWSER=?, BROWSER_VERSION=?, OS=? WHERE P_ID=?"),
	UPDATE_THREADS_TESTNAME("UPDATE THREADS SET TESTNAME=? WHERE P_ID=?"),
	UPDATE_THREADS_BROWSER("UPDATE THREADS SET BROWSER=? WHERE P_ID=?"),
	UPDATE_THREADS_BROWSER_VERSION("UPDATE THREADS SET BROWSER_VERSION=? WHERE P_ID=?"),
	UPDATE_THREADS_OS("UPDATE THREADS SET OS=? WHERE P_ID=?"),
	UPDATE_THREADS_BUILD_FULL_KEY("UPDATE THREADS SET BUILD_FULL_KEY=? WHERE P_ID=?"),
	UPDATE_MASTER_TABLE("UPDATE MASTER_TABLE SET VAL=? WHERE P_ID=? AND KEY_VAL=?"),
	UPDATE_STEP_LEVEL_KEYWORD("UPDATE "
			+ "STEP_LEVEL_REPORT "
			+ "SET "
			+ "KEYWORD=? "
			+ "WHERE "
			+ "P_ID=? "
			+ "AND STEP_NUMBER=?"),
	UPDATE_STEP_LEVEL_PARAMETERS("UPDATE "
			+ "STEP_LEVEL_REPORT "
			+ "SET "
			+ "PARAMETERS=? "
			+ "WHERE "
			+ "P_ID=? "
			+ "AND STEP_NUMBER=?"),
	UPDATE_STEP_LEVEL_DESCRIPTION("UPDATE "
			+ "STEP_LEVEL_REPORT "
			+ "SET "
			+ "DESCRIPTION=? "
			+ "WHERE "
			+ "P_ID=? "
			+ "AND STEP_NUMBER=?"),
	UPDATE_STEP_LEVEL_RESULT("UPDATE "
			+ "STEP_LEVEL_REPORT "
			+ "SET "
			+ "RESULT=? "
			+ "WHERE "
			+ "P_ID=? "
			+ "AND STEP_NUMBER=?"),
	UPDATE_REPORT_TABLE_START_TIME("UPDATE "
			+ "REPORT_TABLE "
			+ "SET "
			+ "START_TIME=? "
			+ "WHERE "
			+ "P_ID=?"),
	UPDATE_REPORT_TABLE_TOTAL_STEPS("UPDATE "
			+ "REPORT_TABLE "
			+ "SET "
			+ "TOTAL_STEPS=? "
			+ "WHERE "
			+ "P_ID=?"),
	UPDATE_REPORT_TABLE_STEPS_PASSED("UPDATE "
			+ "REPORT_TABLE "
			+ "SET "
			+ "STEPS_PASSED=? "
			+ "WHERE "
			+ "P_ID=?"),
	UPDATE_REPORT_TABLE_STEPS_FAILED("UPDATE "
			+ "REPORT_TABLE "
			+ "SET "
			+ "STEPS_FAILED=? "
			+ "WHERE "
			+ "P_ID=?"),
	UPDATE_REPORT_TABLE_TOTAL_EXECUTION_TIME("UPDATE "
			+ "REPORT_TABLE "
			+ "SET "
			+ "TOTAL_EXECUTION_TIME=? "
			+ "WHERE "
			+ "P_ID=?"),
	UPDATE_REPORT_TABLE_RESULT("UPDATE "
			+ "REPORT_TABLE "
			+ "SET "
			+ "RESULT=? "
			+ "WHERE "
			+ "P_ID=?"),
	UPDATE_REPORT_TABLE_SAUCE_VIDEO("UPDATE "
			+ "REPORT_TABLE "
			+ "SET "
			+ "SAUCE_VIDEO=? "
			+ "WHERE "
			+ "P_ID=?"),
	UPDATE_REPORT_TABLE_SPLUNK_SESSION("UPDATE "
			+ "REPORT_TABLE "
			+ "SET "
			+ "SPLUNK_SESSION=? "
			+ "WHERE "
			+ "P_ID=?"),
	UPDATE_REPORT_TABLE_SILO("UPDATE "
			+ "REPORT_TABLE "
			+ "SET "
			+ "SILO=? "
			+ "WHERE "
			+ "P_ID=?"),
	UPDATE_REPORT_TABLE_BUILD("UPDATE "
			+ "REPORT_TABLE "
			+ "SET "
			+ "BUILD=? "
			+ "WHERE "
			+ "P_ID=?"),
	UPDATE_REPORT_TABLE_CONTENT_VERSION("UPDATE "
			+ "REPORT_TABLE "
			+ "SET "
			+ "CONTENT_VERSION=? "
			+ "WHERE "
			+ "P_ID=?"),
	UPDATE_REPORT_TABLE_O_COOKIE("UPDATE "
			+ "REPORT_TABLE "
			+ "SET "
			+ "O_COOKIE=? "
			+ "WHERE "
			+ "P_ID=?"),
	UPDATE_REPORT_TABLE_SET_TO_FAILED("UPDATE REPORT_TABLE SET RESULT = 'Failed' WHERE RESULT='N/A'"),
	UPDATE_RERUN_TABLE_CURRENT_PID_WITH_PREVIOUS_PID("UPDATE RERUN_TABLE SET PREVIOUS_PID=? WHERE CURRENT_PID=?"),
	
	/*
	 * Get
	 */
	GET_COOKIES_VALUE_BY_COOKIE_AND_PID("SELECT VALUE FROM COOKIES WHERE P_ID=? AND NAME=?"),
	GET_COOKIES_ALL_COOKIES_BY_PID("SELECT NAME, DOMAIN, VALUE FROM COOKIES WHERE P_ID=?"),
	GET_COOKIES_ALL_INFORMATION("SELECT TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION, TR.OS, CK.NAME, CK.DOMAIN, CK.VALUE FROM COOKIES CK JOIN THREADS TR ON TR.P_ID=CK.P_ID JOIN BUILD_SCRIPTS BS ON TR.P_ID=BS.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE BD.BUILD_FULL_KEY=? ORDER BY TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION"),
	
	GET_JSERRORS_ALL_INFORMATION("SELECT TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION, TR.OS, JSR.TSTAMP, JSR.URL, JSR.JSERROR FROM JSERROR JSR JOIN THREADS TR ON TR.P_ID = JSR.P_ID JOIN BUILD_SCRIPTS BS ON BS.P_ID = TR.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE BD.BUILD_FULL_KEY = ? ORDER BY TR.P_ID"),
	GET_JSERRORS_SIZE("SELECT COUNT(*) FROM JSERROR JSR JOIN BUILD_SCRIPTS BS ON BS.P_ID=JSR.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE BD.BUILD_FULL_KEY=?"),
	
	GET_RERUN_TABLE_PREVIOUS_PID_FOR_CURRENT_PID("SELECT PREVIOUS_PID FROM RERUN_TABLE WHERE CURRENT_PID=?"),
	GET_RERUN_TABLE_ORIGINAL_AND_RERUN_USING_ORIGINAL_PID("SELECT PREVIOUS_PID AS ORIGINAL, CURRENT_PID AS RERUN FROM RERUN_TABLE WHERE PREVIOUS_PID=?"),
	
	GET_THREADS_ALL_SCRIPTS_RUN_IN_SUITE_INCLUDING_RERUN("SELECT TR.P_ID FROM THREADS TR JOIN BUILD_SCRIPTS BS ON TR.P_ID=BS.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE BD.BUILD_FULL_KEY=?"),
	GET_THREADS_ALL_SCRIPTS_RUN_IN_SUITE_NOT_INCLUDING_RERUN_COUNT("SELECT COUNT(*) FROM (SELECT TR.TESTNAME FROM THREADS TR JOIN BUILD_SCRIPTS BS ON BS.P_ID=TR.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE BD.BUILD_FULL_KEY=? GROUP BY TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION, TR.OS)"),
	GET_THREADS_UNIQUE_SCRIPTS_RUN_IN_SUITE("SELECT DISTINCT(TR.TESTNAME) FROM THREADS TR JOIN BUILD_SCRIPTS BS ON TR.P_ID=BS.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE BD.BUILD_FULL_KEY=?"),
	GET_THREADS_UNIQUE_PID("SELECT DISTINCT TR.P_ID, TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION FROM THREADS TR JOIN BUILD_SCRIPTS BS ON TR.P_ID=BS.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE BD.BUILD_FULL_KEY=?"),
	GET_THREADS_INFORMATION("SELECT DISTINCT TR.P_ID, TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION FROM THREADS TR JOIN BUILD_SCRIPTS BS ON BS.P_ID=TR.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE BD.BUILD_FULL_KEY=? ORDER BY TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION"),
	GET_THREADS_TESTNAME("SELECT TESTNAME FROM THREADS WHERE P_ID=?"),
	GET_THREADS_BROWSER("SELECT BROWSER FROM THREADS WHERE P_ID=?"),
	GET_THREADS_BROWSER_VERSION("SELECT BROWSER_VERSION FROM THREADS WHERE P_ID=?"),
	GET_THREADS_OS("SELECT OS FROM THREADS WHERE P_ID=?"),
	GET_THREADS_THREAD("SELECT THREAD FROM THREADS WHERE P_ID=?"),
	GET_THREADS_INFO_BY_PID("SELECT TESTNAME, BROWSER, BROWSER_VERSION, OS FROM THREADS WHERE P_ID=?"),
	GET_THREADS_SCRIPT_RESULT_BY_SCRIPT_INFORMATION("SELECT RT.RESULT, RT.O_COOKIE, RT.BUILD, RT.CONTENT_VERSION, RT.P_ID FROM THREADS TR , REPORT_TABLE RT, BUILD_SCRIPTS BS, BUILD BD WHERE TR.P_ID=RT.P_ID AND TR.P_ID=BS.P_ID AND BS.BUILD_ID=BD.ID AND TR.TESTNAME=? AND TR.BROWSER=? AND TR.BROWSER_VERSION=? AND TR.OS=? AND BD.BUILD_FULL_KEY=? ORDER BY TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION, RT.START_TIME"),
	GET_THREADS_TABLE_ALL_BROWSERS_RUN_IN_SUITE("SELECT TR.BROWSER, TR.BROWSER_VERSION, TR.OS FROM THREADS TR JOIN BUILD_SCRIPTS BS ON TR.P_ID=BS.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID JOIN REPORT_TABLE RT ON TR.P_ID=RT.P_ID WHERE BD.BUILD_FULL_KEY=? GROUP BY TR.BROWSER, TR.BROWSER_VERSION, TR.OS ORDER BY TR.BROWSER, TR.BROWSER_VERSION, TR.OS"),
	GET_THREADS_TABLE_BROWSER_RESULT_COUNT_BY_BROWSER_OS_INFO("SELECT COUNT(*) AS BROWSER_PASSED FROM THREADS TR JOIN BUILD_SCRIPTS BS ON TR.P_ID=BS.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID JOIN REPORT_TABLE RT ON TR.P_ID=RT.P_ID WHERE RESULT = 'PASSED' AND BD.BUILD_FULL_KEY=? AND TR.BROWSER=? AND TR.BROWSER_VERSION=? AND TR.OS=?"),
	GET_THREADS_P_ID_BY_TEST_NAME_AND_BUILD_KEY("SELECT TR.P_ID FROM THREADS TR JOIN BUILD_SCRIPTS BS ON TR.P_ID=BS.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE BD.BUILD_FULL_KEY=? AND TR.TESTNAME=?"),
	
	GET_MASTER_TABLE_COUNT_OF_KEY("SELECT COUNT(*) FROM (SELECT DISTINCT(TR.TESTNAME) FROM MASTER_TABLE MT JOIN THREADS TR ON MT.P_ID = TR.P_ID JOIN BUILD_SCRIPTS BS ON MT.P_ID=BS.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE MT.KEY_VAL=? AND BD.BUILD_FULL_KEY=?)"),
	GET_MASTER_TABLE_COUNT_OF_KEY_AND_VALUE("SELECT COUNT(*) FROM (SELECT DISTINCT(TR.TESTNAME) FROM MASTER_TABLE MT JOIN THREADS TR ON MT.P_ID = TR.P_ID JOIN BUILD_SCRIPTS BS ON MT.P_ID=BS.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE TR.P_ID NOT IN (SELECT RRT.PREVIOUS_PID FROM RERUN_TABLE RRT) AND MT.KEY_VAL=? AND MT.VAL=? AND BD.BUILD_FULL_KEY=?)"),
	GET_MASTER_TABLE_JAVA_SCRIP_ERRORS("SELECT TR.P_ID, TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION, TR.OS, MT.KEY_VAL, MT.VAL FROM MASTER_TABLE MT JOIN THREADS TR ON TR.P_ID=MT.P_ID WHERE MT.KEY_VAL='jsErrorIncrementValue' OR MT.KEY_VAL LIKE 'jsErrors%' ORDER BY TR.P_ID"),
	GET_MASTER_TABLE_APP_SERVER_URL("SELECT MT.VAL FROM MASTER_TABLE MT JOIN THREADS TR ON TR.P_ID=MT.P_ID WHERE TR.TESTNAME=? AND MT.KEY_VAL='appServerUrl'"),
	GET_MASTER_TABLE_VALUE("SELECT VAL FROM MASTER_TABLE WHERE P_ID=? AND KEY_VAL=?"),
	GET_MASTER_TABLE_INFO_OF_KEY("SELECT * FROM MASTER_TABLE WHERE KEY_VAL=?"),
	GET_MASTER_TABLE_PROD_APP_SERVER_SILO_BY_PID("SELECT PAS.SILO FROM MASTER_TABLE MT JOIN PROD_APP_SERVERS PAS ON PAS.URL=MT.VAL WHERE MT.KEY_VAL='appServerUrl' AND MT.P_ID=?"),
	GET_MASTER_TABLE_QA_APP_SERVER_SILO_BY_PID("SELECT QAS.SILO FROM MASTER_TABLE MT JOIN QA_APP_SERVERS QAS ON QAS.URL=MT.VAL WHERE MT.KEY_VAL='appServerUrl' AND MT.P_ID=?"),
	GET_MASTER_TABLE_PROD_APP_SERVER_SILO_AND_COMPONENT("SELECT PAS.SILO, PAS.COMPONENT FROM PROD_APP_SERVERS PAS JOIN MASTER_TABLE MT ON MT.VAL=PAS.URL JOIN THREADS TR ON TR.P_ID=MT.P_ID WHERE MT.KEY_VAL='appServerUrl' AND TR.TESTNAME=? AND TR.P_ID=?"),
	GET_MASTER_TABLE_QA_APP_SERVER_SILO_AND_COMPONENT("SELECT QAS.SILO FROM QA_APP_SERVERS QAS JOIN MASTER_TABLE MT ON MT.VAL=QAS.URL JOIN THREADS TR ON TR.P_ID=MT.P_ID WHERE MT.KEY_VAL='appServerUrl' AND TR.TESTNAME=? AND TR.P_ID=?"),
	GET_MASTER_TABLE_PROD_APP_SERVER_URL("SELECT PAS.URL FROM PROD_APP_SERVERS PAS JOIN MASTER_TABLE MT ON MT.VAL=PAS.URL JOIN THREADS TR ON TR.P_ID=MT.P_ID WHERE MT.KEY_VAL='appServerUrl' AND TR.TESTNAME=? AND TR.P_ID=?"),
	GET_MASTER_TABLE_QA_APP_SERVER_URL("SELECT QAS.URL FROM QA_APP_SERVERS QAS JOIN MASTER_TABLE MT ON MT.VAL=QAS.URL JOIN THREADS TR ON TR.P_ID=MT.P_ID WHERE MT.KEY_VAL='appServerUrl' AND TR.TESTNAME=? AND TR.P_ID=?"),
	
	
	GET_STEP_LEVEL_REPORT_VALUES_BY_P_ID("SELECT SLT.STEP_NUMBER, SLT.KEYWORD, SLT.PARAMETERS, SLT.DESCRIPTION, SLT.RESULT FROM STEP_LEVEL_REPORT SLT JOIN THREADS TR ON SLT.P_ID = TR.P_ID WHERE TR.P_ID=? ORDER BY TR.TESTNAME, SLT.STEP_NUMBER"),
	GET_STEP_LEVEL_KEYWORD("SELECT "
			+ "KEYWORD "
			+ "FROM " 
			+ "STEP_LEVEL_REPORT "
			+ "WHERE "
			+ "P_ID=? "
			+ "AND STEP_NUMBER=? "),
	GET_STEP_LEVEL_PARAMETERS("SELECT "
			+ "PARAMETERS "
			+ "FROM "
			+ "STEP_LEVEL_REPORT "
			+ "WHERE "
			+ "P_ID=? "
			+ "AND STEP_NUMBER=? "),
	GET_STEP_LEVEL_DESCRIPTION("SELECT "
			+ "DESCRIPTION "
			+ "FROM "
			+ "STEP_LEVEL_REPORT "
			+ "WHERE "
			+ "P_ID=? "
			+ "AND STEP_NUMBER=? "),
	GET_STEP_LEVEL_RESULT("SELECT "
			+ "RESULT "
			+ "FROM "
			+ "STEP_LEVEL_REPORT "
			+ "WHERE "
			+ "P_ID=? "
			+ "AND STEP_NUMBER=? "),
	
	GET_REPORT_TABLE_START_TIME("SELECT "
			+ "START_TIME "
			+ "FROM "
			+ "REPORT_TABLE "
			+ "WHERE "
			+ "P_ID=? "),
	GET_REPORT_TABLE_TOTAL_STEPS("SELECT "
			+ "TOTAL_STEPS "
			+ "FROM "
			+ "REPORT_TABLE "
			+ "WHERE "
			+ "P_ID=? "),
	GET_REPORT_TABLE_STEPS_PASSED("SELECT "
			+ "STEPS_PASSED "
			+ "FROM "
			+ "REPORT_TABLE "
			+ "WHERE "
			+ "P_ID=? "),
	GET_REPORT_TABLE_STEPS_FAILED("SELECT "
			+ "STEPS_FAILED "
			+ "FROM "
			+ "REPORT_TABLE "
			+ "WHERE "
			+ "P_ID=? "),
	GET_REPORT_TABLE_TOTAL_EXECUTION_TIME("SELECT "
			+ "TOTAL_EXECUTION_TIME "
			+ "FROM "
			+ "REPORT_TABLE "
			+ "WHERE "
			+ "P_ID=? "),
	GET_REPORT_TABLE_RESULT("SELECT "
			+ "RESULT "
			+ "FROM "
			+ "REPORT_TABLE "
			+ "WHERE "
			+ "P_ID=? "),
	GET_REPORT_TABLE_SAUCE_VIDEO("SELECT "
			+ "SAUCE_VIDEO "
			+ "FROM "
			+ "REPORT_TABLE "
			+ "WHERE "
			+ "P_ID=? "),
	GET_REPORT_TABLE_SPLUNK_SESSION("SELECT "
			+ "SPLUNK_SESSION "
			+ "FROM "
			+ "REPORT_TABLE "
			+ "WHERE "
			+ "P_ID=? "),
	GET_REPORT_TABLE_SILO("SELECT "
			+ "SILO "
			+ "FROM "
			+ "REPORT_TABLE "
			+ "WHERE "
			+ "P_ID=? "),
	GET_REPORT_TABLE_BUILD("SELECT "
			+ "BUILD "
			+ "FROM "
			+ "REPORT_TABLE "
			+ "WHERE "
			+ "P_ID=? "),
	GET_REPORT_TABLE_CONTENT_VERSION("SELECT "
			+ "START_TIME "
			+ "FROM "
			+ "REPORT_TABLE "
			+ "WHERE "
			+ "P_ID=? "),
	GET_REPORT_TABLE_O_COOKIE("SELECT "
			+ "START_TIME "
			+ "FROM "
			+ "REPORT_TABLE "
			+ "WHERE "
			+ "P_ID=? "),
	GET_REPORT_TABLE_RESULT_BY_TESTNAME("SELECT TR.BROWSER, TR.BROWSER_VERSION, TR.OS, RT.RESULT FROM REPORT_TABLE RT JOIN THREADS TR ON RT.P_ID=TR.P_ID WHERE TR.TESTNAME=? ORDER BY TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION, TR.OS, RT.START_TIME"),
	GET_REPORT_TABLE_RESULT_BY_PID("SELECT RESULT FROM REPORT_TABLE WHERE P_ID=?"),
	GET_REPORT_TABLE_TOTAL_BROWSERS_FROM_SUITE("SELECT TR.BROWSER, TR.BROWSER_VERSION, TR.OS FROM THREADS TR JOIN BUILD_SCRIPTS BS ON TR.P_ID=BS.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID JOIN REPORT_TABLE ON TR.P_ID=RT.P_ID WHERE BD.BUILD_FULL_KEY=? GROUP BY BROWSER, BROWSER_VERSION, OS ORDER BY BROWSER, BROWSER_VERSION, OS"),
	GET_REPORT_ALL_INFORMATION("SELECT TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION, TR.OS, RT.START_TIME, RT.TOTAL_STEPS, RT.STEPS_PASSED, RT.STEPS_FAILED, RT.TOTAL_EXECUTION_TIME, RT.RESULT, RT.SAUCE_VIDEO, RT.SPLUNK_SESSION, RT.SILO, RT.BUILD, RT.CONTENT_VERSION, RT.O_COOKIE, TR.P_ID FROM THREADS TR JOIN REPORT_TABLE RT ON TR.P_ID=RT.P_ID WHERE TR.P_ID=? ORDER BY TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION, RT.START_TIME"),
	GET_REPORT_ALL_PID("SELECT RT.P_ID FROM THREADS TR JOIN REPORT_TABLE RT ON TR.P_ID=RT.P_ID ORDER BY TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION, RT.START_TIME"),
	GET_REPORT_ALL_INFORMATION_BY_PID("SELECT TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION, TR.OS, RT.START_TIME, RT.TOTAL_STEPS, RT.STEPS_PASSED, RT.STEPS_FAILED, RT.TOTAL_EXECUTION_TIME, RT.RESULT, RT.SAUCE_VIDEO, RT.SPLUNK_SESSION, RT.SILO, RT.BUILD, RT.CONTENT_VERSION, RT.O_COOKIE, TR.P_ID FROM THREADS TR JOIN REPORT_TABLE RT ON TR.P_ID=RT.P_ID WHERE RT.P_ID=? ORDER BY TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION, RT.START_TIME"),
	GET_REPORT_TABLE_ALL_INFORMATION_BY_TESTNAME_BROWSER_BROWSER_VERION_OS("SELECT RT.START_TIME, RT.TOTAL_EXECUTION_TIME, RT.RESULT, RT.SAUCE_VIDEO, RT.SPLUNK_SESSION, RT.SILO, RT.BUILD FROM THREADS TR, REPORT_TABLE RT, BUILD_SCRIPTS BS, BUILD BD WHERE TR.P_ID=RT.P_ID AND TR.P_ID=BS.P_ID AND BS.BUILD_ID=BD.ID AND TR.TESTNAME=? AND TR.BROWSER=? AND TR.BROWSER_VERSION=? AND TR.OS=? AND BD.BUILD_FULL_KEY=? ORDER BY TR.TESTNAME, TR.BROWSER, TR.BROWSER_VERSION, RT.START_TIME"),
	GET_REPORT_BUILD_NUMBER("SELECT DISTINCT RT.BUILD FROM REPORT_TABLE RT JOIN BUILD_SCRIPTS BS ON BS.P_ID=RT.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE RT.BUILD <> 'N/A' AND BD.BUILD_FULL_KEY=?"),
	GET_REPORT_SILO("SELECT DISTINCT SILO FROM REPORT_TABLE WHERE BUILD <> 'N/A'"),
	GET_REPORT_CONTENT_VERSION("SELECT DISTINCT CONTENT_VERSION FROM REPORT_TABLE WHERE BUILD <> 'N/A'"),
	GET_REPORT_O_COOKIE("SELECT DISTINCT O_COOKIE FROM REPORT_TABLE WHERE BUILD <> 'N/A'"),
	GET_REPORT_LIST_OF_ALL_TEST_PASSED("SELECT RT.P_ID FROM REPORT_TABLE RT JOIN THREADS TR ON RT.P_ID = TR.P_ID JOIN BUILD_SCRIPTS BS ON TR.P_ID=BS.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE RT.RESULT ='PASSED' AND BD.BUILD_FULL_KEY=?"),
	GET_REPORT_LIST_OF_ALL_TEST_FAILED("SELECT RT.P_ID FROM REPORT_TABLE RT JOIN THREADS TR ON RT.P_ID = TR.P_ID JOIN BUILD_SCRIPTS BS ON TR.P_ID=BS.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE RT.RESULT ='FAILED' AND BD.BUILD_FULL_KEY=?"),
	GET_REPORT_TOTAL_STEPS_PASSED("SELECT SUM(RT.STEPS_PASSED) FROM REPORT_TABLE RT JOIN THREADS TR ON TR.P_ID = RT.P_ID JOIN BUILD_SCRIPTS BS ON BS.P_ID=TR.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE BD.BUILD_FULL_KEY=?"),
	GET_REPORT_TOTAL_STEPS("SELECT SUM(RT.TOTAL_STEPS) FROM REPORT_TABLE RT JOIN THREADS TR ON TR.P_ID = RT.P_ID JOIN BUILD_SCRIPTS BS ON BS.P_ID=TR.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID WHERE BD.BUILD_FULL_KEY=?"),
	GET_REPORT_APP_SERVER_INFORMATION_BY_URL("SELECT TR.TESTNAME, RT.RESULT, RT.SILO, RT.BUILD, RT.CONTENT_VERSION, RT.O_COOKIE FROM MASTER_TABLE MT JOIN BUILD_SCRIPTS BS ON BS.P_ID=MT.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID JOIN REPORT_TABLE RT ON RT.P_ID=MT.P_ID JOIN THREADS TR ON TR.P_ID = MT.P_ID WHERE MT.VAL=? AND BD.BUILD_FULL_KEY=? ORDER BY RT.START_TIME ASC"),
	GET_ALL_SCRIPTS("SELECT * FROM SCRIPTS"),
	GET_SCRIPTS_FOR_LOCAL_DEV_REGRESSION("SELECT SCRIPT_NAME FROM SCRIPTS WHERE LOCAL_DEV_REGRESSION=1"),
	GET_SCRIPTS_SALESFORCE_REGRESSION_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE SALESFORCE_REGRESSION_SUITE=1"),
	GET_SCRIPTS_SALESFORCE_SRG_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE SALESFORCE_SRG_SUITE=1"),
	GET_SCRIPTS_SALES_FORCE_SMOKE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE SALESFORCE_SMOKE_PROD=1"),
	GET_SCRIPTS_ALTQ_REGRESSION("SELECT SCRIPT_NAME FROM SCRIPTS WHERE ALTQREGRESSION=1"),
	GET_SCRIPTS_MMF2("SELECT SCRIPT_NAME FROM SCRIPTS WHERE MMF2=1"),
	GET_SCRIPTS_ADOBE_PROD_OPEN_FOR_BUSINESS_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE ADOBE_PROD_OFB_SUITE=1"),
	GET_SCRIPTS_ADOBE_QA_REGRESSION_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE ADOBE_PROD_OFB_SUITE=1"),
	GET_SCRIPTS_PRODUCTION_OPEN_FOR_BUSINESS_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE PRODUCTION_BUSINESS_SUITE=1"),
	GET_SCRIPTS_HEADLESS_PRODUCTION_OPEN_FOR_BUSINESS_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE PRODUCTION_BUSINESS_SUITE=1"),
	GET_SCRIPTS_MIDTIER_PRODUCTION_OPEN_FOR_BUSINESS_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE MIDTIER_PRODUCTION_OFB=1"),
	GET_SCRIPTS_MIDTIER_QA_REGRESSION_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE MIDTIER_QA_REGRESSION=1"),
	GET_SCRIPTS_MOBILE_ANDROID_OPEN_FOR_BUSINESS_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE MOBILE_ANDROID_OFB=1"),
	GET_SCRIPTS_MOBILE_IOS_OPEN_FOR_BUSINESS_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE MOBILE_IOS_OFB=1"),
	GET_SCRIPTS_MWEB_OPEN_FOR_BUSINESS_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE MWEB_OPEN_FOR_BUSINESS=1"),
	GET_MWEB_REGRESSION_TESTS("SELECT SCRIPT_NAME FROM SCRIPTS WHERE MWEB_REGRESSION=1"),
	GET_SCRIPTS_PRODUCTION_APP_SERVER_OPEN_FOR_BUSINESS_SUITE("SELECT URL FROM PROD_APP_SERVERS"),
	GET_SCRIPTS_PRODUCTION_HOURLY_OPEN_FOR_BUSINESS_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE PRODUCTION_HOURLY_SUITE=1"),
	GET_SCRIPTS_ADOBE_REGRESSION("SELECT SCRIPT_NAME FROM SCRIPTS WHERE ADOBEREGRESSION=1"),
	GET_SCRIPTS_QA_SMOKE_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE SMOKE=1"),
	GET_SCRIPTS_QA_CORE_REGRESSION_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE QA_CORE_REGRESSION_SUITE=1"),
	GET_SCRIPTS_FABORY("SELECT SCRIPT_NAME FROM SCRIPTS WHERE FABORY=1"),
	GET_SCRIPTS_PR_INT("SELECT SCRIPT_NAME FROM SCRIPTS WHERE PR_INT=1"),
	GET_SCRIPTS_MOBILE_API_VALIDATION_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE MOBILE_API_VALIDATION_SUITE=1"),
	GET_SCRIPTS_MOBILE_IPAD_OPEN_FOR_BUSINESS_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE MOBILE_IPAD_OFB=1"),
	GET_SCRIPTS_PRODUCTION_OPEN_FOR_BUSINESS_SILO_SIGN_OFF_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE PRODUCTION_OFB_SIGN_OFF_SUITE=1"),
	GET_SCRIPTS_QA_ZDT_SIGN_OFF("SELECT SCRIPT_NAME FROM SCRIPTS WHERE QAZDTSIGNOFF=1"),
	GET_SCRIPTS_CHECKOUT_REGRESSION_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE CHECKOUT_REGRESSION_SUITE=1"),
	GET_SCRIPTS_CHECKOUT_REGRESSION_EXTENDED_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE CHKOUT_REGR_EXTENDED_SUITE=1"),
	GET_SCRIPTS_MOBILE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE MOBILE=1"),
	GET_SCRIPTS_ZDT_COOKIE("SELECT MAIN_DOMAIN FROM ZDT_SILO_TEST"),
	GET_SCRIPTS_PROD_APP_SERVER_SILO_1("SELECT URL FROM PROD_APP_SERVERS WHERE SILO='Silo 1' OR SILO='Shared'"),
	GET_SCRIPTS_PROD_APP_SERVER_SILO_2("SELECT URL FROM PROD_APP_SERVERS WHERE SILO='Silo 2' OR SILO='Shared'"),
	GET_SCRIPTS_ALTQ_APP_SERVER("SELECT URL FROM ALTQ_APP_SERVERS"),
	GET_SCRIPTS_ALTQ_APP_SERVER_SILO_1("SELECT URL FROM ALTQ_APP_SERVERS WHERE SILO='Silo 1'"),
	GET_SCRIPTS_ALTQ_APP_SERVER_SILO_2("SELECT URL FROM ALTQ_APP_SERVERS WHERE SILO='Silo 2'"),
	GET_SCRIPTS_QA_APP_SERVER("SELECT URL FROM QA_APP_SERVERS"),
	GET_SCRIPTS_QA_APP_SERVER_SILO_1("SELECT URL FROM QA_APP_SERVERS WHERE SILO='1'"),
	GET_SCRIPTS_QA_APP_SERVER_SILO_2("SELECT URL FROM QA_APP_SERVERS WHERE SILO='2'"),
	GET_SCRIPTS_PROD_MOBILE_API("SELECT SCRIPT_NAME FROM SCRIPTS WHERE PROD_MOBILE_API=1"),
	GET_SCRIPTS_MOBILE_API_REGRESSION_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE MOBILE_API_REGRESSION_SUITE=1"),
	GET_SCRIPTS_PRODUCTION_MOBILE_API_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE PRODUCTION_MOBILE_API_SUITE=1"),
	GET_SCRIPTS_SOE_REGRESSION_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE SOE_REGRESSION_SUITE=1"),
	GET_SCRIPTS_SOE_OPEN_FOR_BUSINESS_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE SOE_OPEN_FOR_BUSINESS_SUITE=1"),
	GET_SCRIPTS_SEO_REGRESSION_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE SEO_REGRESSION_SUITE=1"),
	GET_SCRIPTS_ACCOUNT_CUSTOMIZATION_LOCKING_REGRESSION_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE ACCT_CUST_LOCKING_REGRESSION=1"),
	GET_SCRIPTS_CUSTOM_CATALOG_REGRESSION_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE CUSTOM_CATALOG_REGRESSION=1"),
	GET_SCRIPTS_EPRO_REGRESSION_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE EPRO_REGRESSION_SUITE=1"),
	GET_SCRIPTS_LIST_REGRESSION_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE LIST_REGRESSION=1"),
	GET_SCRIPTS_PRICING_REGRESSION_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE PRICING_REGRESSION=1"),
	GET_SCRIPTS_BONGO_EXPORT_REGRESSION_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE BONGO_EXPORT_REGRESSION=1"),
	GET_SCRIPTS_CSAA_REGRESSION_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE CSAA_REGRESSION=1"),
	GET_SCRIPTS_CART_BOP_REGRESSION_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE CART_BOP_REGRESSION=1"),
	GET_SCRIPTS_MAU_REGRESSION_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE MAU_REGRESSION_SUITE=1"),
	GET_SCRIPTS_ANONYMOUS_REGRESSION_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE ANONYMOUS_REGRESSION_SUITE=1"),
	GET_SCRIPTS_KEEPSTOCK_REGRESSION_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE KEEPSTOCK_REGRESSION_SUITE=1"),
	GET_SCRIPTS_OPEN_SEARCH_REGRESSION_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE OPEN_SEARCH_REGRESSION_SUITE=1"),
	GET_SCRIPTS_XREF_OPEN_FOR_BUSINESS_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE XREF_OFB_SUITE=1"),//'XREF_OFB_SUITE' NEEDS TO BE ADDED IN THE SCRIPTS TABLE
	GET_SCRIPTS_PRODUCTION_SERVICES_MONITORING_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE PROD_SERVICES_SUITE=1 AND SCRIPT_NAME <> 'FAUTO1330_PI_Order_Create_USA' AND SCRIPT_NAME <> 'fauto1331_pi_customer_change_usa' AND SCRIPT_NAME <> 'fauto1331_pi_customer_change_usa' AND SCRIPT_NAME <> 'fauto1332_order_response_usa' AND SCRIPT_NAME <> 'fauto1376_accertify_fraud_submit_order' AND SCRIPT_NAME <> 'fauto1377_gp_send_online_leasing_data' AND SCRIPT_NAME <> 'fauto1378_school_dude_order_request' AND SCRIPT_NAME <> 'paymetricsauthorization' AND SCRIPT_NAME <> 'responsysservicecheck' AND SCRIPT_NAME <> 'rtaserviceauthorization'"),
	GET_SCRIPTS_PRODUCTION_NETWORK_TRAFFIC_MONITORING_SUITE("SELECT SCRIPT_NAME FROM SCRIPTS WHERE PROD_NET_TRAFFIC_SUITE=1"),
	GET_SCRIPTS_P_ID_BY_SCRIPT_NAME("SELECT P_ID FROM SCRIPTS WHERE SCRIPT_NAME=?"),
	GET_SCRIPT_PATH_BY_P_ID("SELECT SCRIPT_PATH FROM SCRIPT_PATH WHERE P_ID=?"),
	GET_CREDIT_CARD_ROW("SELECT * FROM CREDIT_CARD WHERE TEST_CASE_TYPE=?"),
	GET_CREDIT_CARD_NAME_ON_CARD("SELECT NAME_ON_CARD FROM CREDIT_CARD WHERE TEST_CASE_TYPE=?"),
	GET_CREDIT_CARD_EXPIRY_YEAR("SELECT EXPIRY_YEAR FROM CREDIT_CARD WHERE TEST_CASE_TYPE=?"),
	GET_SALES_FORCE_ROW("SELECT * FROM SALES_FORCE WHERE TEST_CASE_TYPE=?"),
	GET_USER_REGISTRATION_ROW("SELECT * FROM USER_REGRISTRATION WHERE TEST_CASE_TYPE=?"),
	GET_ITEMS_REGULAR_ITEM("SELECT REGULARITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_CLEARANCE_ITEM("SELECT CLEARANCEITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_ONSALE_ITEM("SELECT ONSALEITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_LESSTHANDOLLAR_ITEM("SELECT LESSTHANDOLLARITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_HAZMAT_ITEM("SELECT HAZMATITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_DISCONTINUED_ITEM("SELECT DISCONTINUEDITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_ACID_ITEM("SELECT ACIDITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_BALLVALVESWITHLEAD_ITEM("SELECT BALLVALVESWITHLEADITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_BALLVALVESWITHOUTLEAD_ITEM("SELECT BALLVALVESWITHOUTLEADITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_LOWLEADWITHALTERNATE_ITEM("SELECT LOWLEADWITHALTERNATEITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_LOWLEADNOALTERNATE_ITEM("SELECT LOWLEADNOALTERNATEITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_LOWLEADWITHA6_ITEM("SELECT LOWLEADWITHA6ITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_LOWLEADWITHA9_ITEM("SELECT LOWLEADWITHA9ITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_STATERESTRICTED_ITEM("SELECT STATERESTRICTEDITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_REFRIGERANT_ITEM("SELECT REFRIGERANTITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_STATUSTP_ITEM("SELECT STATUSTPITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_STATUSST_ITEM("SELECT STATUSSTITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_STATUSLS_ITEM("SELECT STATUSLSITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_STATUSC3_ITEM("SELECT STATUSC3ITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_STATUSC4_ITEM("SELECT STATUSC4ITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_STATUSWH_ITEM("SELECT STATUSWHITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_STATUSPW_ITEM("SELECT STATUSPWITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_STATUSPS_ITEM("SELECT STATUSPSITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_STATUSNC_ITEM("SELECT STATUSNCITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_STATUSNH_ITEM("SELECT STATUSNHITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_STATUSWGWV_ITEM("SELECT STATUSWGWVITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_OHTYPEA_ITEM("SELECT OHITEMTYPEA FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_OHTYPEB_ITEM("SELECT OHITEMTYPEB FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_LIMITEDQTY_ITEM("SELECT LIMITEDQTYITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_TRIPLEGUARD_ITEM("SELECT TRIPLEGUARDITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_PAPERPRODUCT_ITEM("SELECT PAPERPRODUCTITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_INTELLIGENTOFFER_ITEM("SELECT INTELLIGENTOFFERITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_NONINTELLIGENTOFFER_ITEM("SELECT NONINTELLIGENTOFFERITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_RESPIRATORY_ITEM("SELECT RESPIRATORYITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_EXPORTCOMPLIANCE_ITEM("SELECT EXPORTCOMPLIANCEITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_CCSCENARIO1CATALOG_ITEM("SELECT CCSCENARIO1CATALOGITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_CCSCENARIO1NONCATALOG_ITEM("SELECT CCSCENARIO1NONCATALOGITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_CCSCENARIO2CATALOG_ITEM("SELECT CCSCENARIO2CATALOGITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_CCSCENARIO2NONCATALOG_ITEM("SELECT CCSCENARIO2NONCATALOGITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_CCSCENARIO3CATALOG_ITEM("SELECT CCSCENARIO3CATALOGITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_CCSCENARIO3NONCATALOG_ITEM("SELECT CCSCENARIO3NONCATALOGITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_CCSCENARIO4CATALOG_ITEM("SELECT CCSCENARIO4CATALOGITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_CCSCENARIO4NONCATALOG_ITEM("SELECT CCSCENARIO4NONCATALOGITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_VERIFYADDRESSDELETE_ITEM("SELECT VERIFYADDRESSDELETE FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_LOWLEAD_ITEM("SELECT LOWLEADITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_FABORYS_ITEM("SELECT FABORYITEMS FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_INTERNATIONALSALERESTRICTEDHAZ_ITEM("SELECT INTERNATIONALSALERESTRICTEDHAZITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_SEVENCOMBO_ITEM("SELECT SEVENCOMBOITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_SWITHTECHNICALSPECS_ITEM("SELECT ITEMSWITHTECHNICALSPECS FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_NOPICKUP_ITEM("SELECT NOPICKUPITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_PANDEMICORDER_ITEM("SELECT PANDEMICORDERITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_LOWLEADSTATERESTRICTED_ITEM("SELECT LOWLEADSTATERESTRICTEDITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_TAAGSA_ITEM("SELECT TAAGSAITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_CSPACCT0800008369_ITEM("SELECT CSPACCT0800008369ITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_SPECIAL_ITEM("SELECT SPECIALITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_JWOODAB1_ITEM("SELECT JWOODAB1ITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_GSA_ITEM("SELECT GSAITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_ESI_ITEM("SELECT ESIITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_SHIPPACK_ITEM("SELECT SHIPPACKITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_ORPHANCLEANER_ITEM("SELECT ORPHANCLEANER FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_GUESTUSERRESTICTED_ITEM("SELECT GUESTUSERRESTICTED FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_PCARDPRICECHECK_ITEM("SELECT PCARDPRICECHECKITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_ILRESTRICTED_ITEM("SELECT ILRESTRICTEDITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_L3CATEGORY_ITEM("SELECT L3CATEGORYITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_SKUSEARCHSPECIFIC_ITEM("SELECT SKUSEARCHSPECIFICITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_CODE399_ITEM("SELECT ITEMCODE399 FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_PRICECHECK_ITEM("SELECT PRICECHECKITEM FROM ITEMS WHERE P_ID=?"),
	
	
	GET_ITEMS_LTLHAZMATITEM_ITEM("SELECT LTLHAZMATITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_LTLONLYITEM_ITEM("SELECT LTLONLYITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_LTLORITEM_ITEM("SELECT LTLORITEM FROM ITEMS WHERE P_ID=?"),
	GET_ITEMS_ORONLYITEM_ITEM("SELECT ORONLYITEM FROM ITEMS WHERE P_ID=?"),	
	
	GET_PROD_APP_SERVER_ADMIN("SELECT URL FROM PROD_APP_SERVERS WHERE COMPONENT='Admin' ORDER BY URL"),
	GET_PROD_APP_SERVER_BOTS("SELECT URL FROM PROD_APP_SERVERS WHERE COMPONENT='Bots' ORDER BY URL"),
	GET_PROD_APP_SERVER_SILO_1("SELECT URL FROM PROD_APP_SERVERS WHERE SILO LIKE '%1' ORDER BY URL"),
	GET_PROD_APP_SERVER_SILO_2("SELECT URL FROM PROD_APP_SERVERS WHERE SILO LIKE '%2' ORDER BY URL"),
	
	GET_EMPLOYEE_DETAILS_BY_MAC_ADDRESS("SELECT EY.FIRST_NAME, EY.LAST_NAME, EY.RACFID, ED.SAUCE_USERNAME, ED.SAUCE_ACCESS_KEY FROM EMPLOYEE EY JOIN EMPLOYEE_DETAILS ED ON EY.EMPLOYEE_ID = ED.EMPLOYEE_ID WHERE ED.MAC_ADDRESS=?"),
	GET_EMPLOYEE_DETAILS_BY_RACFID("SELECT EY.FIRST_NAME, EY.LAST_NAME, EY.RACFID, ED.SAUCE_USERNAME, ED.SAUCE_ACCESS_KEY FROM EMPLOYEE EY JOIN EMPLOYEE_DETAILS ED ON EY.EMPLOYEE_ID = ED.EMPLOYEE_ID WHERE EY.RACFID=?"),
	GET_EMPLOYEE_DETAILS_GUEST_USER("SELECT EY.FIRST_NAME, EY.LAST_NAME, EY.RACFID, ED.SAUCE_USERNAME, ED.SAUCE_ACCESS_KEY FROM EMPLOYEE EY JOIN EMPLOYEE_DETAILS ED ON EY.EMPLOYEE_ID = ED.EMPLOYEE_ID WHERE ED.EMPLOYEE_ID='0'"),
	GET_EMPLOYEE_DETAILS_BHARATH("SELECT EY.FIRST_NAME, EY.LAST_NAME, EY.RACFID, ED.SAUCE_USERNAME, ED.SAUCE_ACCESS_KEY FROM EMPLOYEE EY JOIN EMPLOYEE_DETAILS ED ON EY.EMPLOYEE_ID = ED.EMPLOYEE_ID WHERE ED.EMPLOYEE_ID='5'"),
	GET_EMPLOYEE_DETAILS_BY_ID("SELECT EY.FIRST_NAME, EY.LAST_NAME, EY.RACFID, ED.SAUCE_USERNAME, ED.SAUCE_ACCESS_KEY FROM EMPLOYEE EY JOIN EMPLOYEE_DETAILS ED ON EY.EMPLOYEE_ID = ED.EMPLOYEE_ID WHERE ED.EMPLOYEE_ID=?"),
	GET_EMPLOYEE_RACFID_BY_FIRST_NAME("Select RACFID from EMPLOYEE WHERE lower(FIRST_NAME)=?"),
	
	GET_PLAN_ID_BY_PLAN_NAME("SELECT ID FROM PLANS WHERE PLAN_NAME=?"),
	GET_BAMBOO_PLAN_NAME_BY_ID("SELECT PLAN_NAME FROM PLANS WHERE ID=?"),
	GET_BAMBOO_PLAN_NAME_BY_PLAN_NAME("SELECT PLAN_NAME FROM PLANS WHERE PLAN_NAME=?"),
	GET_PROD_APP_SERVER_BETA_SERVERS("SELECT URL FROM PROD_APP_SERVERS WHERE SILO LIKE '%3'AND COMPONENT='Beta' ORDER BY URL"),
	GET_BUILD_ID_FROM_BUILD_BY_BUILD_FULL_KEY("SELECT ID FROM BUILD WHERE BUILD_FULL_KEY=?"),
	
	GET_TOTAL_SCRIPTS_RUN_FOR_PLAN("SELECT COUNT(*) FROM REPORT_TABLE RT JOIN THREADS TR ON TR.P_ID=RT.P_ID JOIN BUILD_SCRIPTS BS ON TR.P_ID=BS.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID JOIN PLANS PL ON BD.PLAN_ID=PL.ID WHERE PL.ID IN (SELECT PL.ID FROM PLANS PL JOIN BUILD BD ON BD.PLAN_ID=PL.ID WHERE BD.BUILD_FULL_KEY=?)"),
	GET_TOTAL_PASSED_SCRIPTS_RUN_FOR_PLAN("SELECT COUNT(*) FROM REPORT_TABLE RT JOIN THREADS TR ON TR.P_ID=RT.P_ID JOIN BUILD_SCRIPTS BS ON TR.P_ID=BS.P_ID JOIN BUILD BD ON BD.ID=BS.BUILD_ID JOIN PLANS PN ON BD.PLAN_ID=PN.ID WHERE PN.ID IN (SELECT PN.ID FROM PLANS PN JOIN BUILD BD ON BD.PLAN_ID=PN.ID WHERE BUILD_FULL_KEY=?) AND RT.RESULT='PASSED'"),
	
	GET_SELENIUM_USER_USER_AND_PASSWORD("SELECT SEL_USER, PASSWORD FROM SELENIUM_USERS WHERE USER_TYPE=? AND ENVIRONMENT=?"),
	
	GET_WEB_KS_ORDER_ID("Select WEB_KS_ORDER_NUMBER FROM WEB_KS_ORDER_NUMBERS A, WEB_KS_ORDER_DETAILS B WHERE A.WEB_KS_ID = B.WEB_KS_ID AND WEB_KS_TYPE=? AND WEB_KS_ENVIRONMENT=?"),
	
	GET_SELENIUM_USER_USER_ID("SELECT USER_ID FROM SELENIUM_USERS WHERE SEL_USER=? AND ENVIRONMENT=?"),
	
	GET_SALESFORCE_USER_ID("SELECT SALESFORCE_USER_ID FROM SALESFORCE_USER_ID WHERE SELENIUM_USER_ID=?"),
	
	/*
	 * BROWSER/EMULATORS
	 */
	GET_BROWSERS_ENV_OPTIONS("SELECT BROWSER, BROWSER_VERSION, OS FROM BROWSERS WHERE KEY_VAL=?"),
	GET_EMULATORS_ENV_OPTIONS("SELECT DEVICE_NAME, EMULATOR, EMULATOR_VERSION FROM EMULATORS WHERE KEY_VAL=?"),
	
	/*
	 * SLACK KEYS
	 */
	GET_SLACK_KEY_BY_NAME("SELECT KEY_VAL FROM SLACK_KEYS WHERE NAME=?"),
	
	/*
	 * Drop
	 */
	DROP_THREADS_TABLE("DROP TABLE IF EXISTS THREADS"),
	DROP_MASTER_TABLE("DROP TABLE IF EXISTS MASTER_TABLE"),
	DROP_STEP_LEVEL_REPORT("DROP TABLE IF EXISTS STEP_LEVEL_REPORT"),
	DROP_REPORT_TABLE("DROP TABLE IF EXISTS REPORT_TABLE"),
	DROP_RERUN_TABLE("DROP TABLE IF EXISTS RERUN_TABLE"),
	DROP_JSERROR_TABLE("DROP TABLE IF EXISTS JSERROR"),
	DROP_COOKIES_TABLE("DROP TABLE IF EXISTS COOKIES"),
	
	/*
	 * GCAPTURE
	 */
	GET_GCAPTURE_BRANDS_SUITE("SELECT KEYWORDS FROM GCAPTURE_BRANDS"),
	GET_GCAPTURE_GCOM_IDP_SUITE("SELECT KEYWORDS FROM GCAPTURE_GCOM_IDP"),
	GET_GCAPTURE_GCOM_L2_SUITE("SELECT KEYWORDS FROM GCAPTURE_GCOM_L2"),
	GET_GCAPTURE_KEYWORDS_SUITE("SELECT KEYWORDS FROM GCAPTURE_KEYWORDS"),
	GET_GCAPTURE_KEYWORDS_L1_SUITE("SELECT KEYWORDS FROM GCAPTURE_KEYWORDS_L1"),
	GET_GCAPTURE_KEYWORDS_L2_SUITE("SELECT KEYWORDS FROM GCAPTURE_KEYWORDS_L2"),
	GET_GCAPTURE_KEYWORDS_L3_SUITE("SELECT KEYWORDS FROM GCAPTURE_KEYWORDS_L3"),
	GET_GCAPTURE_LEGAL_SUITE("SELECT KEYWORDS FROM GCAPTURE_LEGAL"),
	GET_GCAPTURE_SITES_SUITE("SELECT KEYWORDS FROM GCAPTURE_SITES"),
	
	/**
	 * SALESFORCE
	 */
	GET_SALESFORCE_PROD_USER_INFORMATION("SELECT ACCOUNT_NUMBER, ACCOUNT_NAME, CONTACT_NUMBER, DOCUMENT_NUMBER, INVOICE_NUMBER, SKU, CONTACT_NAME FROM SF_PROD_USER_INFO WHERE TEST_CASE_TYPE=?"),
	
	/**
	 * Network Analytics
	 */
	GET_NETWORK_DATA_SCRIPT_VALUES_FROM_PAGE_AND_SCRIPT_NAME("SELECT ND_ID, NAME, METHOD, FIELD FROM NETWORK_DATA_SCRIPT WHERE PAGE=? AND SCRIPT_ID=?"),
	GET_NETWORK_DATA_FIELDS_FROM_ND_ID("SELECT PARAMETER_NAME, PARAMETER_VALUE FROM NETWORK_DATA WHERE ND_ID=?"),
	
	/*
	 *BROWSER STATISTICS
	 */
	GET_BUILD_BROWSER_STATISTICS("SELECT BROWSER, BROWSER_VERSION, OS, PASSED, FAILED, PASSED_PERCENT FROM BUIILD_BROWSER_STATISTICS WHERE BUILD_KEY=?");
	
	private String sql;
	
	private QueryVars(String sql){
		this.sql = sql;
	}
	public String getSql(){
		return this.sql;
	}
	public static QueryVars getQueryType(String type){
		for(QueryVars tp: QueryVars.values()){
			if(tp.name().equalsIgnoreCase(type)) return tp;
		}
		return null;
	}
}
